package org.twelve.gcp.exception;

public enum GCPErrCode {
    NODE_AST_MISMATCH, INTERPRETER_NOT_IMPLEMENTED, UNSUPPORTED_BINARY_OPERATION, OUTLINE_MISMATCH,
    UNARY_POSITION_MISMATCH, UNSUPPORTED_UNARY_OPERATION, CONDITION_IS_NOT_BOOL,
    AMBIGUOUS_CALL_MATCH, VARIABLE_NOT_DEFINED, POSSIBLE_ENDLESS_LOOP,
    AMBIGUOUS_VARIABLE_REFERENCE,  MODULE_NOT_DEFINED,
    UNEXPECTED_ERROR, AMBIGUOUS_FUNCTION_DEFINITION, OUTLINE_MISMATCH_IN_GCP, UNREACHABLE_STATEMENT,
    UNAVAILABLE_OUTLINE_ASSIGNMENT, FUNCTION_NOT_DEFINED, NOT_A_FUNCTION, PROJECT_FAIL, FIELD_NOT_FOUND,
    NOT_INITIALIZED, DUPLICATED_DEFINITION, ARGUMENT_MISMATCH, THIS_IS_NOT_ASSIGNABLE, WRONG_THIS_PLACED, INFER_ERROR, NOT_ASSIGNABLE, POLY_SUM_FAIL;

}
